### ISSUE TITLE
Reviving the project

### ISSUE THREAD

**Issue by gavinmasese** [vincentkims49/online-food-order-system#1]
we never got to see the end 

- [x] _ulichoka katikati bro??_

- [x] pesa ilikufunga macho?

**Comment by gavinmasese** [comment]
@vincentkims49

**Comment by vincentkims49** [comment]
> we never got to see the end
> 
> * [x]  _ulichoka katikati bro??_
> * [x]  pesa ilikufunga macho?

> Laptop ikona issue.
> Sina time.
> Am looking for guys who can handle some tasks I'll be issuing. Kuna payout.

**Comment by gavinmasese** [comment]
tasks gani hizo
na payout ni gani

**Comment by vincentkims49** [comment]
Online jobs
Alafu unalipwa ...ni computer science tasks .. mambo na programming

**Comment by vincentkims49** [comment]
Siunitengenezee readme yangu ikae yaku mkuu

**Comment by gavinmasese** [comment]
sijaelewa message ya pili
kweli ntaezana na hizo tasks

**Comment by vincentkims49** [comment]
Nauliza kama unaeza nitengenezea readme file yangu ikae yako GitHub...sina
lapi

Let me attach a file uone tasks naongelelea

**Comment by gavinmasese** [comment]
wazi wacha nikutengeezee repo utakuja ucopy paste

**Comment by vincentkims49** [comment]
Poa
