### ISSUE TITLE
@vincentkims49

### ISSUE THREAD

**Issue by gavinmasese** [vincentkims49/online-food-order-system#2]
@vincentkims49

_Originally posted by @poeticjustice1 in https://github.com/vincentkims49/online-food-order-system/issues/1#issuecomment-1145773633_
buda kwani unafanya nini attacho kama si kucheza na net

**Comment by vincentkims49** [comment]
Nafanya project flani ya flutter nikijifunza

**Comment by gavinmasese** [comment]
https://poeticjustice1.github.io/
enda uonee hioo

**Comment by vincentkims49** [comment]
Thanks, I'll check it out.

**Comment by gavinmasese** [comment]
wacha nifanye changes ntakushow

**Comment by vincentkims49** [comment]
Hadi profile yako hakuna

**Comment by gavinmasese** [comment]
ndio nafanya changes huoni nimechange username

**Comment by gavinmasese** [comment]
Wazi

**Comment by vincentkims49** [comment]
Nasema github

**Comment by gavinmasese** [comment]
https://gavinmasese.github.io/

**Comment by gavinmasese** [comment]
Poa

**Comment by vincentkims49** [comment]
Sioni readme

**Comment by gavinmasese** [comment]
aaah ntachange pia
sijachange we ona portfolio yangu

**Comment by gavinmasese** [comment]
si nimerudisha kaka

**Comment by vincentkims49** [comment]
Wacha nijaribu kujenga yangu

**Comment by gavinmasese** [comment]
wazi

**Comment by vincentkims49** [comment]
How did you do it

**Comment by gavinmasese** [comment]
fork hio repo iko kwa profile yangu inaitwa gavinmasese.github.io na uiite jina ya github yako

**Comment by gavinmasese** [comment]
then kuna process unafuata apo kwa readme

**Comment by vincentkims49** [comment]
I'll call later uniambie

**Comment by gavinmasese** [comment]
wazi haina shida

**Comment by vincentkims49** [comment]
Number?

**Comment by gavinmasese** [comment]
0798403489 piga lunch time niko kazi

**Comment by gavinmasese** [comment]
ebu nitumie articles mbili ivi zenye ziko kwa zile accounts mingi uliandikia

**Comment by vincentkims49** [comment]
Unataka MD files ama

**Comment by gavinmasese** [comment]
ziii natumia diana peters 
si uko na articles miiingi kama 7 ivi

**Comment by gavinmasese** [comment]
ukipiga ntakueleza check portfolio yangi in like 10 minutes

**Comment by vincentkims49** [comment]
Yeah but sina logins juu email nilitoa

**Comment by gavinmasese** [comment]
haina shida
nataka tu hivo articles nizipublish medium alafu zikuje kwa portfolio yangu

**Comment by vincentkims49** [comment]
Section wataraise issue if you do that

**Comment by gavinmasese** [comment]
medium unaimport article we relaxx

**Comment by gavinmasese** [comment]
section ndio wako na copyright

**Comment by gavinmasese** [comment]
https://medium.com/@gavinmasese911/how-to-store-unicode-characters-using-literals-in-java-13e3fdcd8a
ona hio example

**Comment by vincentkims49** [comment]
Section walininua hizo articles so they belong to them and sijui kama Wana
support medium

Articles nimeandika labda usearch writers
Diana peter
Faith zawadi
Geoffrey Kimani
Francisca ngondu

**Comment by gavinmasese** [comment]
kwani hujui vile copyright huuwork
nimetumia ya diana peters solo zingine we unaeza tumia

**Comment by gavinmasese** [comment]
ata hizo za diana hazijatokea niko na yangu na ya mathee

**Comment by gavinmasese** [comment]
<!-- https://alx-intranet.hbtn.io/projects/100007#quiz-completed --!>

**Comment by gavinmasese** [comment]
https://github.com/aws-samples/simple-websockets-chat-app

**Comment by gavinmasese** [comment]
https://kampusville.com/write-internship-attachment-report/

**Comment by gavinmasese** [comment]
https://www.academia.edu/7898523/Indutrial_training_report_format_tybtech_mech

**Comment by vincentkims49** [comment]
Inaleta error buda

**Comment by vincentkims49** [comment]
Unasema IG?

**Comment by gavinmasese** [comment]
https://nevonprojects.com/secure-online-auction-system/
